# TCL File Generated by Component Editor 18.1
# Fri May 20 17:09:06 CST 2022
# DO NOT MODIFY


# 
# memory_tester "memory_tester" v1.0
#  2022.05.20.17:09:06
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module memory_tester
# 
set_module_property DESCRIPTION ""
set_module_property NAME memory_tester
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME memory_tester
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL memory_tester
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi_ctrl.sv SYSTEM_VERILOG PATH axi_ctrl.sv
add_fileset_file divide.v VERILOG PATH divide.v
add_fileset_file memory_tester.sv SYSTEM_VERILOG PATH memory_tester.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter WIDTH INTEGER 32
set_parameter_property WIDTH DEFAULT_VALUE 32
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter ALEN INTEGER 31
set_parameter_property ALEN DEFAULT_VALUE 31
set_parameter_property ALEN DISPLAY_NAME ALEN
set_parameter_property ALEN TYPE INTEGER
set_parameter_property ALEN UNITS None
set_parameter_property ALEN ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ALEN HDL_PARAMETER true
add_parameter START_ADDR STD_LOGIC_VECTOR 0
set_parameter_property START_ADDR DEFAULT_VALUE 0
set_parameter_property START_ADDR DISPLAY_NAME START_ADDR
set_parameter_property START_ADDR WIDTH 34
set_parameter_property START_ADDR TYPE STD_LOGIC_VECTOR
set_parameter_property START_ADDR UNITS None
set_parameter_property START_ADDR ALLOWED_RANGES 0:17179869183
set_parameter_property START_ADDR HDL_PARAMETER true
add_parameter STOP_ADDR STD_LOGIC_VECTOR 1048576
set_parameter_property STOP_ADDR DEFAULT_VALUE 1048576
set_parameter_property STOP_ADDR DISPLAY_NAME STOP_ADDR
set_parameter_property STOP_ADDR WIDTH 34
set_parameter_property STOP_ADDR TYPE STD_LOGIC_VECTOR
set_parameter_property STOP_ADDR UNITS None
set_parameter_property STOP_ADDR ALLOWED_RANGES 0:17179869183
set_parameter_property STOP_ADDR HDL_PARAMETER true
add_parameter ID_WIDTH INTEGER 8
set_parameter_property ID_WIDTH DEFAULT_VALUE 8
set_parameter_property ID_WIDTH DISPLAY_NAME ID_WIDTH
set_parameter_property ID_WIDTH TYPE INTEGER
set_parameter_property ID_WIDTH UNITS None
set_parameter_property ID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ID_WIDTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 32
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 32
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter WUSER_WIDTH INTEGER 1
set_parameter_property WUSER_WIDTH DEFAULT_VALUE 1
set_parameter_property WUSER_WIDTH DISPLAY_NAME WUSER_WIDTH
set_parameter_property WUSER_WIDTH TYPE INTEGER
set_parameter_property WUSER_WIDTH UNITS None
set_parameter_property WUSER_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WUSER_WIDTH HDL_PARAMETER true
add_parameter AWUSER_WIDTH INTEGER 1
set_parameter_property AWUSER_WIDTH DEFAULT_VALUE 1
set_parameter_property AWUSER_WIDTH DISPLAY_NAME AWUSER_WIDTH
set_parameter_property AWUSER_WIDTH TYPE INTEGER
set_parameter_property AWUSER_WIDTH UNITS None
set_parameter_property AWUSER_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AWUSER_WIDTH HDL_PARAMETER true
add_parameter RUSER_WIDTH INTEGER 1
set_parameter_property RUSER_WIDTH DEFAULT_VALUE 1
set_parameter_property RUSER_WIDTH DISPLAY_NAME RUSER_WIDTH
set_parameter_property RUSER_WIDTH TYPE INTEGER
set_parameter_property RUSER_WIDTH UNITS None
set_parameter_property RUSER_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property RUSER_WIDTH HDL_PARAMETER true
add_parameter BUSER_WIDTH INTEGER 1
set_parameter_property BUSER_WIDTH DEFAULT_VALUE 1
set_parameter_property BUSER_WIDTH DISPLAY_NAME BUSER_WIDTH
set_parameter_property BUSER_WIDTH TYPE INTEGER
set_parameter_property BUSER_WIDTH UNITS None
set_parameter_property BUSER_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BUSER_WIDTH HDL_PARAMETER true
add_parameter ARUSER_WIDTH INTEGER 1
set_parameter_property ARUSER_WIDTH DEFAULT_VALUE 1
set_parameter_property ARUSER_WIDTH DISPLAY_NAME ARUSER_WIDTH
set_parameter_property ARUSER_WIDTH TYPE INTEGER
set_parameter_property ARUSER_WIDTH UNITS None
set_parameter_property ARUSER_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ARUSER_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end pass pass Output 1


# 
# connection point altera_axi4_master
# 
add_interface altera_axi4_master axi4 start
set_interface_property altera_axi4_master associatedClock clock
set_interface_property altera_axi4_master associatedReset reset_sink
set_interface_property altera_axi4_master readIssuingCapability 1
set_interface_property altera_axi4_master writeIssuingCapability 1
set_interface_property altera_axi4_master combinedIssuingCapability 1
set_interface_property altera_axi4_master ENABLED true
set_interface_property altera_axi4_master EXPORT_OF ""
set_interface_property altera_axi4_master PORT_NAME_MAP ""
set_interface_property altera_axi4_master CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4_master SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4_master awid awid Output ID_WIDTH
add_interface_port altera_axi4_master awaddr awaddr Output ADDR_WIDTH
add_interface_port altera_axi4_master awlen awlen Output 8
add_interface_port altera_axi4_master awsize awsize Output 3
add_interface_port altera_axi4_master awburst awburst Output 2
add_interface_port altera_axi4_master awlock awlock Output 1
add_interface_port altera_axi4_master awcache awcache Output 4
add_interface_port altera_axi4_master awprot awprot Output 3
add_interface_port altera_axi4_master awqos awqos Output 4
add_interface_port altera_axi4_master awregion awregion Output 4
add_interface_port altera_axi4_master awuser awuser Output AWUSER_WIDTH
add_interface_port altera_axi4_master awvalid awvalid Output 1
add_interface_port altera_axi4_master awready awready Input 1
add_interface_port altera_axi4_master wdata wdata Output WIDTH
add_interface_port altera_axi4_master wstrb wstrb Output WIDTH/8
add_interface_port altera_axi4_master wlast wlast Output 1
add_interface_port altera_axi4_master wuser wuser Output WUSER_WIDTH
add_interface_port altera_axi4_master wvalid wvalid Output 1
add_interface_port altera_axi4_master wready wready Input 1
add_interface_port altera_axi4_master bid bid Input ID_WIDTH
add_interface_port altera_axi4_master bresp bresp Input 2
add_interface_port altera_axi4_master buser buser Input BUSER_WIDTH
add_interface_port altera_axi4_master bvalid bvalid Input 1
add_interface_port altera_axi4_master bready bready Output 1
add_interface_port altera_axi4_master arid arid Output ID_WIDTH
add_interface_port altera_axi4_master araddr araddr Output ADDR_WIDTH
add_interface_port altera_axi4_master arlen arlen Output 8
add_interface_port altera_axi4_master arsize arsize Output 3
add_interface_port altera_axi4_master arburst arburst Output 2
add_interface_port altera_axi4_master arlock arlock Output 1
add_interface_port altera_axi4_master arcache arcache Output 4
add_interface_port altera_axi4_master arprot arprot Output 3
add_interface_port altera_axi4_master arqos arqos Output 4
add_interface_port altera_axi4_master arregion arregion Output 4
add_interface_port altera_axi4_master aruser aruser Output ARUSER_WIDTH
add_interface_port altera_axi4_master arvalid arvalid Output 1
add_interface_port altera_axi4_master arready arready Input 1
add_interface_port altera_axi4_master rid rid Input ID_WIDTH
add_interface_port altera_axi4_master rdata rdata Input WIDTH
add_interface_port altera_axi4_master rresp rresp Input 2
add_interface_port altera_axi4_master rlast rlast Input 1
add_interface_port altera_axi4_master ruser ruser Input RUSER_WIDTH
add_interface_port altera_axi4_master rvalid rvalid Input 1
add_interface_port altera_axi4_master rready rready Output 1

