# TCL File Generated by Component Editor 18.1
# Fri Nov 17 13:17:29 CST 2023
# DO NOT MODIFY


# 
# owl_dma_read "owl_dma_read" v1.0
#  2023.11.17.13:17:29
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module owl_dma_read
# 
set_module_property DESCRIPTION ""
set_module_property NAME owl_dma_read
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME owl_dma_read
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL dma_read
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file dma_read.sv SYSTEM_VERILOG PATH dma_read.sv


# 
# parameters
# 
add_parameter WIDTH INTEGER 1280
set_parameter_property WIDTH DEFAULT_VALUE 1280
set_parameter_property WIDTH DISPLAY_NAME WIDTH
set_parameter_property WIDTH TYPE INTEGER
set_parameter_property WIDTH UNITS None
set_parameter_property WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property WIDTH HDL_PARAMETER true
add_parameter HEIGHT INTEGER 960
set_parameter_property HEIGHT DEFAULT_VALUE 960
set_parameter_property HEIGHT DISPLAY_NAME HEIGHT
set_parameter_property HEIGHT TYPE INTEGER
set_parameter_property HEIGHT UNITS None
set_parameter_property HEIGHT ALLOWED_RANGES -2147483648:2147483647
set_parameter_property HEIGHT HDL_PARAMETER true
add_parameter PW INTEGER 32
set_parameter_property PW DEFAULT_VALUE 32
set_parameter_property PW DISPLAY_NAME PW
set_parameter_property PW TYPE INTEGER
set_parameter_property PW UNITS None
set_parameter_property PW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property PW HDL_PARAMETER true
add_parameter AW INTEGER 32
set_parameter_property AW DEFAULT_VALUE 32
set_parameter_property AW DISPLAY_NAME AW
set_parameter_property AW TYPE INTEGER
set_parameter_property AW UNITS None
set_parameter_property AW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property AW HDL_PARAMETER true
add_parameter DW INTEGER 64
set_parameter_property DW DEFAULT_VALUE 64
set_parameter_property DW DISPLAY_NAME DW
set_parameter_property DW TYPE INTEGER
set_parameter_property DW UNITS None
set_parameter_property DW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DW HDL_PARAMETER true
add_parameter DMA_BL INTEGER 3
set_parameter_property DMA_BL DEFAULT_VALUE 3
set_parameter_property DMA_BL DISPLAY_NAME DMA_BL
set_parameter_property DMA_BL TYPE INTEGER
set_parameter_property DMA_BL UNITS None
set_parameter_property DMA_BL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DMA_BL HDL_PARAMETER true
add_parameter BL INTEGER 4
set_parameter_property BL DEFAULT_VALUE 4
set_parameter_property BL DISPLAY_NAME BL
set_parameter_property BL TYPE INTEGER
set_parameter_property BL UNITS None
set_parameter_property BL ALLOWED_RANGES -2147483648:2147483647
set_parameter_property BL HDL_PARAMETER true
add_parameter APB_AW INTEGER 5
set_parameter_property APB_AW DEFAULT_VALUE 5
set_parameter_property APB_AW DISPLAY_NAME APB_AW
set_parameter_property APB_AW TYPE INTEGER
set_parameter_property APB_AW UNITS None
set_parameter_property APB_AW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property APB_AW HDL_PARAMETER true
add_parameter ID STD_LOGIC_VECTOR 3301
set_parameter_property ID DEFAULT_VALUE 3301
set_parameter_property ID DISPLAY_NAME ID
set_parameter_property ID WIDTH 34
set_parameter_property ID TYPE STD_LOGIC_VECTOR
set_parameter_property ID UNITS None
set_parameter_property ID ALLOWED_RANGES 0:17179869183
set_parameter_property ID HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 cpb_r read Input 1
add_interface_port avalon_slave_0 cpb_w write Input 1
add_interface_port avalon_slave_0 cpb_a address Input APB_AW
add_interface_port avalon_slave_0 cpb_d writedata Input 32
add_interface_port avalon_slave_0 cpb_q readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink rst_n reset_n Input 1


# 
# connection point interrupt_sender
# 
add_interface interrupt_sender interrupt end
set_interface_property interrupt_sender associatedAddressablePoint ""
set_interface_property interrupt_sender associatedClock clock
set_interface_property interrupt_sender associatedReset reset_sink
set_interface_property interrupt_sender bridgedReceiverOffset ""
set_interface_property interrupt_sender bridgesToReceiver ""
set_interface_property interrupt_sender ENABLED true
set_interface_property interrupt_sender EXPORT_OF ""
set_interface_property interrupt_sender PORT_NAME_MAP ""
set_interface_property interrupt_sender CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender irq irq Output 1


# 
# connection point dst_str
# 
add_interface dst_str avalon_streaming start
set_interface_property dst_str associatedClock clock
set_interface_property dst_str associatedReset reset_sink
set_interface_property dst_str dataBitsPerSymbol 8
set_interface_property dst_str errorDescriptor ""
set_interface_property dst_str firstSymbolInHighOrderBits true
set_interface_property dst_str maxChannel 0
set_interface_property dst_str readyLatency 0
set_interface_property dst_str ENABLED true
set_interface_property dst_str EXPORT_OF ""
set_interface_property dst_str PORT_NAME_MAP ""
set_interface_property dst_str CMSIS_SVD_VARIABLES ""
set_interface_property dst_str SVD_ADDRESS_GROUP ""

add_interface_port dst_str dst_str_d data Output PW
add_interface_port dst_str dst_str_rdy ready Input 1
add_interface_port dst_str dst_str_val valid Output 1


# 
# connection point src_bus
# 
add_interface src_bus avalon start
set_interface_property src_bus addressUnits SYMBOLS
set_interface_property src_bus associatedClock clock
set_interface_property src_bus associatedReset reset_sink
set_interface_property src_bus bitsPerSymbol 8
set_interface_property src_bus burstOnBurstBoundariesOnly false
set_interface_property src_bus burstcountUnits WORDS
set_interface_property src_bus doStreamReads false
set_interface_property src_bus doStreamWrites false
set_interface_property src_bus holdTime 0
set_interface_property src_bus linewrapBursts false
set_interface_property src_bus maximumPendingReadTransactions 0
set_interface_property src_bus maximumPendingWriteTransactions 0
set_interface_property src_bus readLatency 0
set_interface_property src_bus readWaitTime 1
set_interface_property src_bus setupTime 0
set_interface_property src_bus timingUnits Cycles
set_interface_property src_bus writeWaitTime 0
set_interface_property src_bus ENABLED true
set_interface_property src_bus EXPORT_OF ""
set_interface_property src_bus PORT_NAME_MAP ""
set_interface_property src_bus CMSIS_SVD_VARIABLES ""
set_interface_property src_bus SVD_ADDRESS_GROUP ""

add_interface_port src_bus src_bus_raddr address Output AW
add_interface_port src_bus src_bus_rdata readdata Input DW
add_interface_port src_bus src_bus_rdval readdatavalid Input 1
add_interface_port src_bus src_bus_rlen burstcount Output BL
add_interface_port src_bus src_bus_rrdy waitrequest_n Input 1
add_interface_port src_bus src_bus_rval read Output 1

