# TCL File Generated by Component Editor 18.1
# Wed Jul 27 16:06:19 CST 2022
# DO NOT MODIFY


# 
# ddr3_wrapper "ddr3_wrapper" v2.0
#  2022.07.27.16:06:19
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module ddr3_wrapper
# 
set_module_property DESCRIPTION ""
set_module_property NAME ddr3_wrapper
set_module_property VERSION 2.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ddr3_wrapper
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL ddr_slave_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file ddr_slave_wrapper.sv SYSTEM_VERILOG PATH ddr_slave_wrapper.sv TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 128
set_parameter_property DATA_WIDTH DEFAULT_VALUE 128
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 32
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 32
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter ID_WIDTH INTEGER 8
set_parameter_property ID_WIDTH DEFAULT_VALUE 8
set_parameter_property ID_WIDTH DISPLAY_NAME ID_WIDTH
set_parameter_property ID_WIDTH TYPE INTEGER
set_parameter_property ID_WIDTH UNITS None
set_parameter_property ID_WIDTH ALLOWED_RANGES -2147483648:2147483647
set_parameter_property ID_WIDTH HDL_PARAMETER true
add_parameter FW INTEGER 3
set_parameter_property FW DEFAULT_VALUE 3
set_parameter_property FW DISPLAY_NAME FW
set_parameter_property FW TYPE INTEGER
set_parameter_property FW UNITS None
set_parameter_property FW ALLOWED_RANGES -2147483648:2147483647
set_parameter_property FW HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink CMSIS_SVD_VARIABLES ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink aclk clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink aresetn reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock_sink
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end wr_ack wr_ack Input 1
add_interface_port conduit_end wr_addr wr_addr Output 32
add_interface_port conduit_end wr_addr_en wr_addr_en Output 1
add_interface_port conduit_end wr_busy wr_busy Input 1
add_interface_port conduit_end wr_data wr_data Output DATA_WIDTH
add_interface_port conduit_end wr_datamask wr_datamask Output DATA_WIDTH/8
add_interface_port conduit_end wr_en wr_en Output 1
add_interface_port conduit_end rd_ack rd_ack Input 1
add_interface_port conduit_end rd_addr rd_addr Output 32
add_interface_port conduit_end rd_addr_en rd_addr_en Output 1
add_interface_port conduit_end rd_busy rd_busy Input 1
add_interface_port conduit_end rd_data rd_data Input DATA_WIDTH
add_interface_port conduit_end rd_en rd_en Output 1
add_interface_port conduit_end rd_valid rd_valid Input 1


# 
# connection point altera_axi4_slave
# 
add_interface altera_axi4_slave axi4 end
set_interface_property altera_axi4_slave associatedClock clock_sink
set_interface_property altera_axi4_slave associatedReset reset_sink
set_interface_property altera_axi4_slave readAcceptanceCapability 1
set_interface_property altera_axi4_slave writeAcceptanceCapability 1
set_interface_property altera_axi4_slave combinedAcceptanceCapability 1
set_interface_property altera_axi4_slave readDataReorderingDepth 1
set_interface_property altera_axi4_slave bridgesToMaster ""
set_interface_property altera_axi4_slave ENABLED true
set_interface_property altera_axi4_slave EXPORT_OF ""
set_interface_property altera_axi4_slave PORT_NAME_MAP ""
set_interface_property altera_axi4_slave CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4_slave SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4_slave awid awid Input ID_WIDTH
add_interface_port altera_axi4_slave awaddr awaddr Input ADDR_WIDTH
add_interface_port altera_axi4_slave awlen awlen Input 8
add_interface_port altera_axi4_slave awsize awsize Input 3
add_interface_port altera_axi4_slave awburst awburst Input 2
add_interface_port altera_axi4_slave awlock awlock Input 1
add_interface_port altera_axi4_slave awcache awcache Input 4
add_interface_port altera_axi4_slave awprot awprot Input 3
add_interface_port altera_axi4_slave awqos awqos Input 4
add_interface_port altera_axi4_slave awregion awregion Input 4
add_interface_port altera_axi4_slave awvalid awvalid Input 1
add_interface_port altera_axi4_slave awready awready Output 1
add_interface_port altera_axi4_slave wdata wdata Input DATA_WIDTH
add_interface_port altera_axi4_slave wstrb wstrb Input DATA_WIDTH/8
add_interface_port altera_axi4_slave wlast wlast Input 1
add_interface_port altera_axi4_slave wvalid wvalid Input 1
add_interface_port altera_axi4_slave wready wready Output 1
add_interface_port altera_axi4_slave bid bid Output ID_WIDTH
add_interface_port altera_axi4_slave bresp bresp Output 2
add_interface_port altera_axi4_slave bvalid bvalid Output 1
add_interface_port altera_axi4_slave bready bready Input 1
add_interface_port altera_axi4_slave arid arid Input ID_WIDTH
add_interface_port altera_axi4_slave araddr araddr Input ADDR_WIDTH
add_interface_port altera_axi4_slave arlen arlen Input 8
add_interface_port altera_axi4_slave arsize arsize Input 3
add_interface_port altera_axi4_slave arburst arburst Input 2
add_interface_port altera_axi4_slave arlock arlock Input 1
add_interface_port altera_axi4_slave arcache arcache Input 4
add_interface_port altera_axi4_slave arprot arprot Input 3
add_interface_port altera_axi4_slave arqos arqos Input 4
add_interface_port altera_axi4_slave arregion arregion Input 4
add_interface_port altera_axi4_slave arvalid arvalid Input 1
add_interface_port altera_axi4_slave arready arready Output 1
add_interface_port altera_axi4_slave rid rid Output ID_WIDTH
add_interface_port altera_axi4_slave rdata rdata Output DATA_WIDTH
add_interface_port altera_axi4_slave rresp rresp Output 2
add_interface_port altera_axi4_slave rlast rlast Output 1
add_interface_port altera_axi4_slave rvalid rvalid Output 1
add_interface_port altera_axi4_slave rready rready Input 1

