# TCL File Generated by Component Editor 18.1
# Wed Aug 31 09:51:15 CST 2022
# DO NOT MODIFY


# 
# axi_uart_read "axi_uart_read" v1.0
#  2022.08.31.09:51:15
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module axi_uart_read
# 
set_module_property DESCRIPTION ""
set_module_property NAME axi_uart_read
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME axi_uart_read
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL axi_uart_read
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file axi_uart_read.sv SYSTEM_VERILOG PATH axi_uart_read.sv TOP_LEVEL_FILE
add_fileset_file usart_rx.v VERILOG PATH usart_rx.v
add_fileset_file usart_tx.v VERILOG PATH usart_tx.v


# 
# parameters
# 
add_parameter DATA_WIDTH INTEGER 128
set_parameter_property DATA_WIDTH DEFAULT_VALUE 128
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE INTEGER
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH HDL_PARAMETER true
add_parameter ADDR_WIDTH INTEGER 32
set_parameter_property ADDR_WIDTH DEFAULT_VALUE 32
set_parameter_property ADDR_WIDTH DISPLAY_NAME ADDR_WIDTH
set_parameter_property ADDR_WIDTH TYPE INTEGER
set_parameter_property ADDR_WIDTH UNITS None
set_parameter_property ADDR_WIDTH HDL_PARAMETER true
add_parameter ID_WIDTH INTEGER 8
set_parameter_property ID_WIDTH DEFAULT_VALUE 8
set_parameter_property ID_WIDTH DISPLAY_NAME ID_WIDTH
set_parameter_property ID_WIDTH TYPE INTEGER
set_parameter_property ID_WIDTH UNITS None
set_parameter_property ID_WIDTH HDL_PARAMETER true
add_parameter ID INTEGER 0
set_parameter_property ID DEFAULT_VALUE 0
set_parameter_property ID DISPLAY_NAME ID
set_parameter_property ID TYPE INTEGER
set_parameter_property ID UNITS None
set_parameter_property ID HDL_PARAMETER true
add_parameter CLOCK_FRQ INTEGER 100000000
set_parameter_property CLOCK_FRQ DEFAULT_VALUE 100000000
set_parameter_property CLOCK_FRQ DISPLAY_NAME CLOCK_FRQ
set_parameter_property CLOCK_FRQ TYPE INTEGER
set_parameter_property CLOCK_FRQ UNITS None
set_parameter_property CLOCK_FRQ HDL_PARAMETER true
add_parameter BADRATE INTEGER 115200
set_parameter_property BADRATE DEFAULT_VALUE 115200
set_parameter_property BADRATE DISPLAY_NAME BADRATE
set_parameter_property BADRATE TYPE INTEGER
set_parameter_property BADRATE UNITS None
set_parameter_property BADRATE HDL_PARAMETER true
add_parameter UART_BIT INTEGER 8
set_parameter_property UART_BIT DEFAULT_VALUE 8
set_parameter_property UART_BIT DISPLAY_NAME UART_BIT
set_parameter_property UART_BIT TYPE INTEGER
set_parameter_property UART_BIT UNITS None
set_parameter_property UART_BIT HDL_PARAMETER true
add_parameter FW INTEGER 4
set_parameter_property FW DEFAULT_VALUE 4
set_parameter_property FW DISPLAY_NAME FW
set_parameter_property FW TYPE INTEGER
set_parameter_property FW UNITS None
set_parameter_property FW HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset_sink_1
# 
add_interface reset_sink_1 reset end
set_interface_property reset_sink_1 associatedClock clock
set_interface_property reset_sink_1 synchronousEdges DEASSERT
set_interface_property reset_sink_1 ENABLED true
set_interface_property reset_sink_1 EXPORT_OF ""
set_interface_property reset_sink_1 PORT_NAME_MAP ""
set_interface_property reset_sink_1 CMSIS_SVD_VARIABLES ""
set_interface_property reset_sink_1 SVD_ADDRESS_GROUP ""

add_interface_port reset_sink_1 rst_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end uart_rx uart_rx Input 1
add_interface_port conduit_end uart_tx uart_tx Output 1


# 
# connection point altera_axi4_master
# 
add_interface altera_axi4_master axi4 start
set_interface_property altera_axi4_master associatedClock clock
set_interface_property altera_axi4_master associatedReset reset_sink_1
set_interface_property altera_axi4_master readIssuingCapability 1
set_interface_property altera_axi4_master writeIssuingCapability 1
set_interface_property altera_axi4_master combinedIssuingCapability 1
set_interface_property altera_axi4_master ENABLED true
set_interface_property altera_axi4_master EXPORT_OF ""
set_interface_property altera_axi4_master PORT_NAME_MAP ""
set_interface_property altera_axi4_master CMSIS_SVD_VARIABLES ""
set_interface_property altera_axi4_master SVD_ADDRESS_GROUP ""

add_interface_port altera_axi4_master awid awid Output ID_WIDTH
add_interface_port altera_axi4_master awaddr awaddr Output ADDR_WIDTH
add_interface_port altera_axi4_master awlen awlen Output 8
add_interface_port altera_axi4_master awsize awsize Output 3
add_interface_port altera_axi4_master awburst awburst Output 2
add_interface_port altera_axi4_master awlock awlock Output 1
add_interface_port altera_axi4_master awcache awcache Output 4
add_interface_port altera_axi4_master awprot awprot Output 3
add_interface_port altera_axi4_master awqos awqos Output 4
add_interface_port altera_axi4_master awregion awregion Output 4
add_interface_port altera_axi4_master awvalid awvalid Output 1
add_interface_port altera_axi4_master awready awready Input 1
add_interface_port altera_axi4_master wdata wdata Output DATA_WIDTH
add_interface_port altera_axi4_master wstrb wstrb Output DATA_WIDTH/8
add_interface_port altera_axi4_master wlast wlast Output 1
add_interface_port altera_axi4_master wvalid wvalid Output 1
add_interface_port altera_axi4_master wready wready Input 1
add_interface_port altera_axi4_master bid bid Input ID_WIDTH
add_interface_port altera_axi4_master bresp bresp Input 2
add_interface_port altera_axi4_master bvalid bvalid Input 1
add_interface_port altera_axi4_master bready bready Output 1
add_interface_port altera_axi4_master arid arid Output ID_WIDTH
add_interface_port altera_axi4_master araddr araddr Output ADDR_WIDTH
add_interface_port altera_axi4_master arlen arlen Output 8
add_interface_port altera_axi4_master arsize arsize Output 3
add_interface_port altera_axi4_master arburst arburst Output 2
add_interface_port altera_axi4_master arlock arlock Output 1
add_interface_port altera_axi4_master arcache arcache Output 4
add_interface_port altera_axi4_master arprot arprot Output 3
add_interface_port altera_axi4_master arqos arqos Output 4
add_interface_port altera_axi4_master arregion arregion Output 4
add_interface_port altera_axi4_master arvalid arvalid Output 1
add_interface_port altera_axi4_master arready arready Input 1
add_interface_port altera_axi4_master rid rid Input ID_WIDTH
add_interface_port altera_axi4_master rdata rdata Input DATA_WIDTH
add_interface_port altera_axi4_master rresp rresp Input 2
add_interface_port altera_axi4_master rlast rlast Input 1
add_interface_port altera_axi4_master rvalid rvalid Input 1
add_interface_port altera_axi4_master rready rready Output 1

